### ISSUE TITLE
issues wireflow

### ISSUE THREAD

**Issue by DaanCarst** [Daan645/fix-the-flow-wireflow#5]
- Plaats de user story boven de wireflows, hierdoor word het sneller duidelijk waar de wireflow overgaat.
- Maak een korte beschrijving van de wireflow en plaats deze onder de wireflow's.
- Maak een pointer waarmee je duidelijk kan maken dat er geklikt kan worden.
- Voor de rest zien de schetsen er prima uit.
- Goed duidelijk gemaakt wie de opdrachtgever is.

**Comment by Daan645** [comment]
Bedankt voor de feedback, ik heb het opgelost! Zie onderstaande afbeeldingen.
![image](https://github.com/Daan645/fix-the-flow-wireflow/assets/54812898/e78912d8-f42c-4ab5-874a-8fa0939f59f5)
![image](https://github.com/Daan645/fix-the-flow-wireflow/assets/54812898/b49cb075-5a82-453c-8866-1708408f98fb)
